### ISSUE TITLE
Not able to get the users plugin working

### ISSUE THREAD

**Issue by djjudas21** [dcsobral/puppet-users#1]
Hi,

I've installed this plugin by copying it into my $modulepath. I've then added individual @useraccount{} declarations to a manifest in my resnet-users module, as in your example.

Trouble is, I'm getting this error:

err: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find resource type useraccount at /etc/puppet/modules/resnet-users/manifests/init.pp:14 on node espresso.resnet.bris.ac.uk

I've included "users" in the basenode definition and I've tried including it explicitly on the server in question (espresso).

What else should I be looking at?

Cheers,
Jonathan

**Comment by dcsobral** [comment]
Well, it should be @users::useraccount, though I see that the README is, in fact, in error in this regard. Could you try it like that and give feedback if that solves for you? Also, the module is supposed to be called "users", even though on github it is called puppet-users.

**Comment by djjudas21** [comment]
Thanks for your reply. I had already named the module "users" but now I've added the @users:: prefix, it seems to work happily.

Cheers,
Jonathan

**Comment by dcsobral** [comment]
Ok, documentation corrected.
