### ISSUE TITLE
README File

### ISSUE THREAD

**Issue by fugit** [dcsobral/puppet-users#2]
First thanks for posting this module looks good so far. Had a problem after using the README file example and the new 2.6 error message made it more painful then need be.  There is a typo in the README:
@users::useracount { "bob":
 should be 
@users::useraccount { "bob":

I also had to define a fullname. 

Thanks, 
Keith.

**Comment by dcsobral** [comment]
Thanks for the report. I have now fixed the example.

On Thu, Mar 10, 2011 at 17:08, fugit <
reply@reply.github.com>wrote:

> First thanks for posting this module looks good so far. Had a problem after
> using the README file example and the new 2.6 error message made it more
> painful then need be.  There is a typo in the README:
> @users::useracount { "bob":
>  should be
> @users::useraccount { "bob":
> 
> I also had to define a fullname.
> 
> Thanks,
> Keith.
> 
> https://github.com/dcsobral/puppet-users/issues/2

## 

Daniel C. Sobral

I travel to the future all the time.

**Comment by dcsobral** [comment]
Thanks for the comments. This has been fixed now.
