### ISSUE TITLE
users::lookupkey duplicating key 

### ISSUE THREAD

**Issue by fugit** [dcsobral/puppet-users#3]
First thanks for a great module. 

I am running puppet 2.6.2 on client and master. I have defined a user  users::lookupkey
      users::lookupkey { 'svndeploy':
        ensure => present, # default value
      }
The line from extdata is below. The problem I am having is it keeps creating the key everytime I run puppet on the client. Please let me know if you need any additional information. 

The line from the extdata file common.csv (key has been changed): 
svndeploy_sshkey,,no-port-forwarding,ssh-dss,AAAAB3NzaC1kc3MxxxCBAMDWxARclzvgY3Q5XpaJEfiV9Pl9yEiO26CxruPFtu9khvBzM2JjdM2lUmZjuaaS2Cp3YguKLJlyOs5MJSujlrpQhNLwZ/Ik4qWBjyefxGAsGwn7PVBblahlahblahRAAAAFQCrmIeqBRtw2mOblahblahblahfKbXj3mO7zRPbIVNpWk3KBBIwZYplmiGp4+m0rBBwNSEY4vxsSTCnhuSInqF21wnNV1P95PETgbf9FVPd5qLPEokrAB97vruclxxxTty9USao0CDc9Lxxx1R9CzY2UG5xgxQiHTJsu+NozAPUTNNDpAzBC914ZX8xxxCAF3qcUrnN0PFKxxxCcnyOxG7DZ8TfvWrBPp424P7V5kOG+w6zZc3OD61Wr1XPDb1SRpKnuAfpy8czmUnUCTAxxxpGFz4N3cUwkpbRK4PPXtUeDgFAQDsXiUQqhk46PYvO/Dt+r7++f47hp5CEu9Lf1aTcXIaO17D4W7NHXy/RaWY= svn@host,post-commit

**Comment by dcsobral** [comment]
There's an extra comma between svndeploy_sshkey and no-port-forwarding.
Since no-port-forwarding is an option, it should come right after the key.
Also, there should be a comma between the end of the key and its comment
(svn@host.post-commit).

On Fri, Apr 1, 2011 at 10:44, fugit <
reply@reply.github.com>wrote:

> First thanks for a great module.
> 
> I am running puppet 2.6.2 on client and master. I have defined a user
>  users::lookupkey
>      users::lookupkey { 'svndeploy':
>        ensure => present, # default value
>      }
> The line from extdata is below. The problem I am having is it keeps
> creating the key everytime I run puppet on the client. Please let me know if
> you need any additional information.
> 
> The line from the extdata file common.csv (key has been changed):
> svndeploy_sshkey,,no-port-forwarding,ssh-dss,AAAAB3NzaC1kc3MxxxCBAMDWxARclzvgY3Q5XpaJEfiV9Pl9yEiO26CxruPFtu9khvBzM2JjdM2lUmZjuaaS2Cp3YguKLJlyOs5MJSujlrpQhNLwZ/Ik4qWBjyefxGAsGwn7PVBblahlahblahRAAAAFQCrmIeqBRtw2mOblahblahblahfKbXj3mO7zRPbIVNpWk3KBBIwZYplmiGp4+m0rBBwNSEY4vxsSTCnhuSInqF21wnNV1P95PETgbf9FVPd5qLPEokrAB97vruclxxxTty9USao0CDc9Lxxx1R9CzY2UG5xgxQiHTJsu+NozAPUTNNDpAzBC914ZX8xxxCAF3qcUrnN0PFKxxxCcnyOxG7DZ8TfvWrBPp424P7V5kOG+w6zZc3OD61Wr1XPDb1SRpKnuAfpy8czmUnUCTAxxxpGFz4N3cUwkpbRK4PPXtUeDgFAQDsXiUQqhk46PYvO/Dt+r7++f47hp5CEu9Lf1aTcXIaO17D4W7NHXy/RaWY=
> svn@host,post-commit
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dcsobral/puppet-users/issues/3

## 

Daniel C. Sobral

I travel to the future all the time.

**Comment by fugit** [comment]
Thanks that would do it. 

Thanks for the help.

----- Original message -----

> There's an extra comma between svndeploy_sshkey and no-port-forwarding.
> Since no-port-forwarding is an option, it should come right after the
> key. Also, there should be a comma between the end of the key and its
> comment (svn@host.post-commit).
> 
> On Fri, Apr 1, 2011 at 10:44, fugit <

**Comment by fugit** [comment]
dsobral: 
Just wanted to confirm that fixed everything for me. I had pasted in the key and failed to notice the comment that had been include. 

Thanks again for the great module and the quick assistance in trouble shooting my issue. 

Keith.
