### ISSUE TITLE
errors while using users:account for user creation

### ISSUE THREAD

**Issue by vjakkina** [dcsobral/puppet-users#5]
Hi,

I am trying to use the puppet-users module to manage the users creation in my test-environment. After the module installation, I have added the definitions in nodes.pp so as to create a test user Bob as below- 

---

node 'ubuntu' {
    include user-creation
}

class user-creation {
    users::account { "bob":
    ensure   => present,
        fullname => "Uncle Bob",
        uid      => 10000,
        #groups   => [ "wheel" ], # Extra groups, defaults to none
        shell    => '/bin/bash', # default value
        password => 'hash',
    }
## }

Puppet agent throws error while parsing the module. Here is the exact error.

---

root@ubuntu-sql:~# puppet agent --server="ubuntu" --certname="ubuntu-sql" --no-daemonize --verbose
notice: Starting Puppet client version 2.7.6
info: Caching catalog for ubuntu-sql
info: Applying configuration version '1323187672'
err: /Stage[main]/User-creation/Users::Account[bob]/File[/home/bob]: Failed to generate additional resources using 'eval_generate: Error 400 on SERVER: Not authorized to call search on /file_metadata/files/users/home/default/host/bob.ubuntu-sql.localdomain with {:ignore=>["_.git", "_.swp", "*.un~"], :recurse=>true, :links=>"manage", :checksum_type=>"md5"}
err: /Stage[main]/User-creation/Users::Account[bob]/File[/home/bob]: Could not evaluate: Error 400 on SERVER: Not authorized to call find on /file_metadata/files/users/home/default/host/bob.ubuntu-sql.localdomain Could not retrieve file metadata for puppet:///files/users/home/default/host/bob.ubuntu-sql.localdomain: Error 400 on SERVER: Not authorized to call find on /file_metadata/files/users/home/default/host/bob.ubuntu-sql.localdomain at /etc/puppet/modules/users/manifests/definitions/account.pp:97
notice: /Stage[main]/User-creation/Users::Account[bob]/File[/home/bob/.ssh]: Dependency File[/home/bob] has failures: true
warning: /Stage[main]/User-creation/Users::Account[bob]/File[/home/bob/.ssh]: Skipping because of failed dependencies
notice: /Stage[main]/User-creation/Users::Account[bob]/File[/home/bob/.bash_history]: Dependency File[/home/bob] has failures: true
warning: /Stage[main]/User-creation/Users::Account[bob]/File[/home/bob/.bash_history]: Skipping because of failed dependencies
## notice: Finished catalog run in 0.11 seconds

Can you please help me out in getting the module working.

Many Thanks,
venu

**Comment by dcsobral** [comment]
Given the error messages, there seems to be some permission problem. Please ensure that the paths to /etc/puppet/files and /etc/puppet/modules/users/files and all their subdirectories are readable and executable by all, and that /etc/puppet/auth.conf and /etc/puppet/fileserver.conf both give enough permissions for your clients to read these files.

Try disabling the users module, and trying to copy files to the home directories from the indicated places with file statements.

**Comment by vjakkina** [comment]
Hi, thanks a lot for your reply.  The indicated files were not available at the /etc/puppet/modules/users/files. They are empty directories. Does these files get created automatically?  I looked at the permissions aspect, all directories have 755 on them. There is no specific deny rule in /etc/puppet/fileserver.conf

**Comment by dcsobral** [comment]
This, at least, should exist: /etc/puppet/modules/users/files/home/default. It, and _all of its ancestors_, need permission 755.

On fileserver.conf, you need to put allow rules. Something like this:

[files]
  path /etc/puppet/files
  allow 192.168.0.0/16

[plugins]
  allow 192.168.0.0/16

[modules]
  allow 192.168.0.0/16

Note the last (modules) rule, which, iirc, is not there by default. Put one such rule for each network that needs access to files in puppet. And, again, please verify that you can use file resources -- there's no point in debugging the module if that isn't working.

**Comment by vjakkina** [comment]
Hi, can you please confirm the sample usage of the module just to manage user-accounts.

## Only change required would be to the /etc/puppet/manifests/nodes.pp file.

node 'ubuntu' {
include user-creation
}

class user-creation {
users::useraccount { "bob":
ensure => present,
fullname => "Uncle Bob",
uid => 10000,
#groups => [ "wheel" ], # Extra groups, defaults to none
shell => '/bin/bash', # default value
password => 'hash',

## }

Can you please clarify how are the passwords taken care of? If the module is pushed to 2 machines, with a class to create user Bob, would i be needing to manually set the password, ssh-keys etc?

**Comment by dcsobral** [comment]
The easiest way to handle the password is to set the password by hand on one machine that has puppet installed, and then do something like "ralsh user bob", which should display the password hash for the password (among other attributes).

However, this only works with Debian-based systems. Puppet does not support password change on RedHat-based systems. See documentation for "user" for what attributes can or cannot be setted in each system.

Have you solved the previous issues, then?

**Comment by vjakkina** [comment]
Hi,

## Previous issues are still there.I have tried installing the module on another puppet-server and tried testing it. Ended up with the similar errors.

err: /Stage[main]/User_management/Users::Useraccount[pilotuser]/File[/home/pilotuser]: Failed to generate additional resources using 'eval_generate: Error 400 on SERVER: Not authorized to call search on /file_metadata/files/users/home/default/host/pilotuser.puptest01.amnesty.org with {:ignore=>".git", :recurse=>true, :links=>"manage", :checksum_type=>"md5"}

## err: /Stage[main]/User_management/Users::Useraccount[pilotuser]/File[/home/pilotuser]: Could not evaluate: Error 400 on SERVER: Not authorized to call find on /file_metadata/files/users/home/default/host/pilotuser.puptest01.amnesty.org Could not retrieve file metadata for puppet:///files/users/home/default/host/pilotuser.puptest01.amnesty.org: Error 400 on SERVER: Not authorized to call find on /file_metadata/files/users/home/default/host/pilotuser.puptest01.amnesty.org at /etc/puppet/modules/users/manifests/definitions/useraccount.pp:85

**Comment by soakes** [comment]
Hi there,

First of all I would like to thank dcsobral for making this awesome module.  I was about to write one myself which done the same as I personally use extlookups for nearly everything and this has it all built in already so this find has saved me hours of work, thank you dcsobral for sharing.  I am just about to tweak it slightly so things are called with the same structure I use for csv data.  Anyway.. moving on..

I have also experienced this same issue which vjakkina had/has but have solved the problem and thought I would share.  This is resolved by adjusting your puppet fileserver.conf file which you should find located in /etc/puppet.  Make sure you have an entry like mine which is shown below.  Replace *.example.com with your domain and it should/will work or you can lock it down to your IP ranges etc.  

Note:  You may find entries like this already exist but commented.  Make sure you have an allow line as by default it seems to deny everything.

[files]
  path /etc/puppet/files
  allow *.example.com

[plugins]
   allow *.example.com

Hope this helps anyone else with this same issue.

Don't forget to restart apache (assuming passenger is being used with puppet) or puppetmaster if your not.

Kind Regards,

Simon

**Comment by soakes** [comment]
With regards to working out the hash password to use for a given user.. the easiest way I have found to solve this is to use the "ralsh user" command.  Use this after you have created a test user with whatever password you want then copy the password hash line enclosed in quote marks. 

There are other ways but this is the easiest solution to understand as its in puppet format already.  Example is shown below from a dev box of mine with a random(ish) password:

user { 'bob':
    comment => 'Uncle Bob,,,',
    home => '/home/bob',
    uid => '10000',
    shell => '/bin/bash',
    ensure => 'present',
    gid => '10000',
    password => '$6$GcowiL.t$TWkrP3PozdeKL/lFJaHRLwPocLzFdQPiMkGssmFQKUbmmHLyIBVnsyrKOD06ZwTlPIc/tfBYZSyvo0tNJRj6V.'
}

or you can just use...

root@alpha:~# grep bob /etc/shadow | cut -d ":" -f2
$6$GcowiL.t$TWkrP3PozdeKL/lFJaHRLwPocLzFdQPiMkGssmFQKUbmmHLyIBVnsyrKOD06ZwTlPIc/tfBYZSyvo0tNJRj6V.

Kind Rehards,

Simon
